# Brewfile — formulae + casks (Homebrew Bundle)
# PHP / Composer / Valet: install via PHP Monitor Setup Assistant, not here.

tap "nicoverbruggen/homebrew-cask"

brew "coreutils"
brew "findutils"
brew "bash"
brew "grep"
brew "vim"
brew "htop"
brew "wget"
brew "tmux"
brew "git"
brew "git-lfs"
brew "lsd"
brew "mise"

cask "iterm2"
cask "orbstack"
cask "dbngin"
cask "tableplus"
cask "figma"
cask "firefox"
cask "slack"
cask "phpmon"
cask "cursor"
cask "visual-studio-code"
cask "1password"
cask "1password-cli"
cask "raycast"
cask "google-chrome"
cask "cyberduck"
cask "discord"
cask "zoom"
cask "spotify"
cask "vlc"
cask "handbrake"
cask "taphouse"
cask "betterdisplay"
cask "bruno"
cask "linear"
cask "logitune"
cask "font-meslo-lg-nerd-font"
cask "font-jetbrains-mono"
